---
functional:
  - Пользователь должен иметь возможность менять язык интерфейса
  - Приложение должно поддерживать локализацию на русский и английский языки
non-functional:
  - Требование 3
  - Требование 4
implicit:
  - Требование 5
  - Требование 6
